version: "3"

services:
  bot:
    environment:
      - PORT=3000
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:${PORT}"
    command: ["uwsgi", "--http", ":${PORT}", "--enable-threads", "--module", "bot.app:app"]
